name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Faz checkout do repositório
      - uses: actions/checkout@v3

      # 2. Gera o snake animation
      - uses: Platane/snk@v3
        with:
          github_user_name: eduardoferreiralima
          outputs: dist/github-contribution-grid-snake.svg

      # 3. Debug: lista arquivos gerados
      - name: List dist folder
        run: ls -R dist

      # 4. Configura Git
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # 5. Push para a branch 'output'
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
